---
- name: Install docker
  gather_facts: No
  hosts: all-hosts

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes
    
    - name: Add user ansible to docker group
      user:
        name: ansible
        group: docker
        append: yes
      become: yes

- name: Init vagrant master
  hosts: host03
  become: yes
  tasks: 
    
    - name: Create docker cluster
      shell: docker swarm init --advertise-addr eth1
    
    - name: Docker get master for join
      shell: docker swarm join-token -q worker
      register: docker_token

- name: Add dockers slave to the cluster
  hosts: docker-slave
  tasks:
    # - name: echo docker token
    #   shell: echo "{{ hostvars['host03']['docker_token']['stdout'] }}" > /tmp/1.txt
    - name: add slaves to the cluster
      shell: sudo docker swarm join --token "{{ hostvars['host03']['docker_token']['stdout'] }}" 192.168.11.13:2377