---
  - hosts: nfs-server
    roles:
    - { role: 'nfs', nfs_mode: 'server', nfs_exports: [{path: "/opt", export: "host*(fsid=0,rw,async,no_root_squash,no_subtree_check,insecure)"}] }
    
    
  - hosts: nfs-client
    roles:
    # - { role: 'nfs', nfs_mode: 'client', nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "{{hostvars['host03']['ansible_default_ipv4']}}" }] }
    - { role: 'nfs', nfs_mode: 'client', nfs_client_imports: [{ local: "/opt", remote: "/opt", server_host: "192.168.11.13" }] }